# Client Test for Room and Booking Services

### 1. **Test for Creating a Booking**
POST http://localhost:8081/bookings
Content-Type: application/json

{
    "roomId": 1,
    "userName": "111",
    "date": "2025-05-02",
    "startTime": "09:00",
    "endTime": "12:00"
}


### 4. **Test for Canceling a Booking**
DELETE http://localhost:8081/bookings/6

### 5. **Test for Getting Room Details**
GET http://localhost:8080/rooms/1


### 6. **Test for Getting All Rooms**
GET http://localhost:8080/rooms
